{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: influx-telegraf-ds-viewer
  labels:
    {{- include "telegraf-ds.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "telegraf-ds.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: influx:telegraf-ds
{{- end }}