apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
data:
  telegraf.conf: |+
    {{- $tplVersion := include "telegraf.detect.version" . }}
    {{ template "telegraf.global_tags" .Values.config.global_tags }}
    {{ template "telegraf.agent" .Values.config.agent }}
    {{ template "telegraf.processors" (list $tplVersion .Values.config.processors) }}
    {{ template "telegraf.aggregators" (list $tplVersion .Values.config.aggregators) }}
    {{ template "telegraf.outputs" (list $tplVersion .Values.config.outputs) }}
    {{- if .Values.metrics.health.enabled }}
    [[outputs.health]]
      service_address = "{{ .Values.metrics.health.service_address }}"
      namepass = ["internal_write"]
      [[outputs.health.compares]]
        field = "buffer_size"
        lt = {{ .Values.metrics.health.threshold | int64 }}.0
      [[outputs.health.contains]]
        field = "buffer_size"
    {{- end }}
    {{ template "telegraf.inputs" (list $tplVersion .Values.config.inputs) }}
    {{- if .Values.metrics.internal.enabled }}
    [[inputs.internal]]
      collect_memstats = {{ or .Values.metrics.internal.collect_memstats (.Values.metrics.collect_memstats | default false) }}
    {{- end }}
